/**
 * Sample Access Code Flow OAuth2 Project
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Repo } from './repo';


export interface Model200 { 
    /**
     * (more repos)
     */
    repos?: Array<Repo>;
}

