/**
 * Sample Access Code Flow OAuth2 Project
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RepoImage } from './repoImage';


export interface Repo { 
    /**
     * the name of the repo
     */
    name?: string;
    /**
     * the description of the repo
     */
    description?: string;
    /**
     * (more images)
     */
    images?: Array<RepoImage>;
}

